FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir scrapy psycopg2-binary

COPY parser/ ./parser/

CMD ["/bin/sh", "-c", "while true; do cd /app/parser && scrapy crawl cbr; sleep 86400; done"]
