# User field lengths
USER_EMAIL_MAX_LEN = 255
USER_USERNAME_MAX_LEN = 100
USER_HASHED_PASSWORD_MAX_LEN = 255

# Currency field lengths
CURRENCY_CHAR_CODE_MAX_LEN = 10
CURRENCY_NUM_CODE_MAX_LEN = 10
CURRENCY_NAME_MAX_LEN = 255

# ExchangeRate numeric precision
EXCHANGE_RATE_PRECISION = 18
EXCHANGE_RATE_SCALE = 6
